baseURL = "http://localhost"
languageCode = "en-gb"
title = "Local EA Website"
theme = "local-ea-template"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
[params]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Site Title"
  strapline = "Helping you do good better"

  ## -- EA GROUP INFO -- ##
  legalOrgName = "Effective Altruism <City Here>"
  orgLocations = "this location and that location"
  registeredCharityNumber = "3.14159"

  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link
  facbookUrl = ""
  twitterUrl = ""
  meetupUrl = ""

  ## -- NAVIGATION BAR HEADERS -- ##
  # You will need to change these if your page is not in English;
  # otherwise, you can leave these alone
  navBarHome = "Home"
  navBarAbout= "About"
  navBarEffectiveAltruism = "Effective Altruism"
  navBarReadingMaterial = "Reading Material"
  navBarKeyTerms = "Key Terms"
  navBarOrganizations = "Organizations"
  navBarContact= "Contact Us"

  ## -- BUTTONS -- ##
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page
  firstButtonText = "First Button Text"
  firstButtonURL = ""
  secondButtonText = "Second Button Text"
  secondButtonURL = ""
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"

  ## -- ABOUT PAGE -- ##
  aboutBannerText = "About us"

  ## -- CONTACT PAGE -- ##
  contactBannerText = "Contact us"
