baseURL = "http://localhost"
languageCode = "en-gb"
title = "Local EA Website"
theme = "local-ea-template"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
[params]
  # General site params
  fullTitle = "Effective Altruism Site Title"
  strapline = "Helping you do good better"

  # EA Group Info
  legalOrgName = "Effective Altruism <City Here>"
  orgLocations = "this location and that location"
  registeredCharityNumber = "3.14159"

  # Group URLs
  # If your group does not have URLs for these, just add # before the line
  # to comment it out
  facbookUrl = ""
  twitterUrl = ""
  meetupUrl = ""

  # Buttons under the main header
  # You can use them to link to a mailing list or Facebook page
  firstButtonText = "First Button Text"
  firstButtonURL = ""
  secondButtonText = "Second Button Text"
  secondButtonURL = ""
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  # Front page text; change as needed.
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  firstSectionText = "We want to help you use evidence and reason to make the world a better place."
  secondSectionHeader = "Building a community"
  secondSectionText = "We are a welcoming group dedicated to promoting, inspiring and supporting one another to achieve altruistic goals."
  thirdSectionHeader = "Finding better ways to help"
  thirdSectionText = "Some projects are thousands of times more effective than others. We apply logic and research to maximise our impact."
  bottomBannerText = "A proud member of the effective altruism network"
